language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "pypy"
- "pypy3"

before_install:
- curl -O https://dl.dropboxusercontent.com/u/3065276/testimages.zip
- unzip testimages.zip
- curl -O https://dl.dropboxusercontent.com/u/3065276/ffmpeg-2.1.3-64bit-static.tar.bz2
- tar jxf ffmpeg-2.1.3-64bit-static.tar.bz2
- sudo cp ffmpeg-2.1.3-64bit-static/ffmpeg /usr/bin
- curl -O https://dl.dropboxusercontent.com/u/3065276/haarcascade_frontalface_alt.xml
# - sudo add-apt-repository ppa:gijzelaar/opencv2.4 -y
# - sudo apt-get update --allow-unauthenticated
# - sudo apt-get install --allow-unauthenticated libopencv-dev
- if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get install python-tk; fi

install:
# - pip install -r requirements.txt Don't need numpy or psutil yet

# Coverage 4.0 doesn't support Python 3.2
- if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install coverage<4; fi
- if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi

- pip install Pillow
- pip install coveralls
before_script:
- chmod +x *.py
script:
- coverage erase
- ./test_pixel_tools.py
after_success:
  coveralls
  pip install pep8 pyflakes
  pep8 --statistics --count *.py
  pyflakes *.py  | tee >(wc -l)

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "pypy"
    - python: "pypy3"
  fast_finish: true
