language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "pypy"
before_install:
- curl -O https://dl.dropboxusercontent.com/u/3065276/testimages.zip
- unzip testimages.zip
- sudo apt-get install ubuntu-restricted-extras ffmpeg
install:
# - pip install -r requirements.txt Don't need numpy or psutil yet
- pip install Pillow
- pip install coveralls
before_script:
- chmod +x *.py
script:
- coverage erase
- ./test_pixel_tools.py
after_success:
  coveralls

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "pypy"
