language: python
python:
- '2.7'
before_install:
- curl -O https://dl.dropboxusercontent.com/u/3065276/testimages.zip
- unzip testimages.zip
install:
- pip install -r requirements.txt
before_script:
- chmod +x test_pixel_tools.py
script: ./test_pixel_tools.py
