language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "pypy"
before_install:
- curl -O https://dl.dropboxusercontent.com/u/3065276/testimages.zip
- unzip testimages.zip
- curl -O https://dl.dropboxusercontent.com/u/3065276/ffmpeg-2.1.3-64bit-static.tar.bz2
- tar jxf ffmpeg-2.1.3-64bit-static.tar.bz2
- sudo cp ffmpeg-2.1.3-64bit-static/ffmpeg /usr/bin
- curl -O https://dl.dropboxusercontent.com/u/3065276/haarcascade_frontalface_alt.xml
- sudo apt-get update
- sudo apt-get install python-opencv
install:
# - pip install -r requirements.txt Don't need numpy or psutil yet
- pip install Pillow
- pip install coveralls
before_script:
- chmod +x *.py
script:
- coverage erase
- ./test_pixel_tools.py
after_success:
  coveralls

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "pypy"
